#define MATERIAL_DIRECTORY CMAKE_PROJ_DIRECTORY "/resources"
#define SHADERS_DIRECTORY MATERIAL_DIRECTORY "/Shaders"
#define SCREEN_SPACE_SHADERS_DIRECTORY SHADERS_DIRECTORY "/Screen-Space_Shaders"
#define AUDIO_DIRECTORY MATERIAL_DIRECTORY "/audio"